#ifndef SIMULATION_UTILITIES_GLOBAL_H
#define SIMULATION_UTILITIES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMULATION_UTILITIES_LIBRARY)
#  define SIMULATION_UTILITIESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIMULATION_UTILITIESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMULATION_UTILITIES_GLOBAL_H
