#ifndef SIMULATION_MATH_GLOBAL_H
#define SIMULATION_MATH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMULATION_MATH_LIBRARY)
#  define SIMULATION_MATHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIMULATION_MATHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMULATION_MATH_GLOBAL_H
